/**
 * Database type definitions for Supabase
 * These will be automatically generated by running:
 * npx supabase gen types typescript --project-id your-project-id > src/types/database.types.ts
 *
 * For now, these are placeholder types based on our schema design.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Product = Database["public"]["Tables"]["products"]["Row"]
export type ProductVariant = Database["public"]["Tables"]["product_variants"]["Row"]
export type ProductSize = Database["public"]["Tables"]["product_sizes"]["Row"]

export type ProductWithRelations = Product & {
  product_variants: (ProductVariant & { product_sizes: ProductSize[] })[]
}

// Products table
export interface Database {
  public: {
    Tables: {
      products: {
        Row: {
          id: string
          name: string
          description: string | null
          category: string
          is_available: boolean
          image_url: string | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          category?: string
          is_available?: boolean
          image_url?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          category?: string
          is_available?: boolean
          image_url?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
      product_variants: {
        Row: {
          id: string
          product_id: string
          name: string
          description: string | null
          sort_order: number
          created_at: string
        }
        Insert: {
          id?: string
          product_id: string
          name: string
          description?: string | null
          sort_order?: number
          created_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          name?: string
          description?: string | null
          sort_order?: number
          created_at?: string
        }
      }
      product_sizes: {
        Row: {
          id: string
          product_id: string
          variant_id: string
          name: string
          volume_gr: number
          price_modifier: number
          stock_quantity: number
          sku: string | null
          created_at: string
        }
        Insert: {
          id?: string
          product_id: string
          variant_id: string
          name: string
          volume_gr: number
          price_modifier?: number
          stock_quantity?: number
          sku?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          variant_id?: string
          name?: string
          volume_gr?: number
          price_modifier?: number
          stock_quantity?: number
          sku?: string | null
          created_at?: string
        }
      }
      orders: {
        Row: {
          id: string
          order_number: string
          customer_name: string
          customer_email: string
          customer_phone: string | null
          total_amount: number
          status: string
          items: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_number: string
          customer_name: string
          customer_email: string
          customer_phone?: string | null
          total_amount: number
          status?: string
          items: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_number?: string
          customer_name?: string
          customer_email?: string
          customer_phone?: string | null
          total_amount?: number
          status?: string
          items?: Json
          created_at?: string
          updated_at?: string
        }
      }
      admin_users: {
        Row: {
          id: string
          role: string
          is_active: boolean
          last_login: string | null
          created_at: string
        }
        Insert: {
          id: string
          role?: string
          is_active?: boolean
          last_login?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          role?: string
          is_active?: boolean
          last_login?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
